module: dnsmasq
name: hits
id: dnsmasq_hits

transformation: true
aggregation: true

filtering: "filter('system.type', 'prometheus-exporter')"

signals:
  signal:
    metric: dnsmasq_hits

rules:
  critical:
    threshold: 1
    comparator: "<="
    lasting_duration: '5m'
